name: Production CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.18.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.18.0
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
